version: '3.8'

services:

  jpbft:
    build:
      context: .
    environment:
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: always

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${password}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
