version: '3.8'

services:

  jpbft:
    build:
      context: .
    environment:
      - BOT_USERNAME=JavaTelegramImageFinder_bot
      - BOT_TOKEN=5198520290:AAEtDCpb2VKhl6AifoXcLG1odp9FVHQ5fKQ
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/nekodb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
    networks:
      - nekonet


  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: 'nekodb'
      POSTGRES_USER: 'nekouser'
      POSTGRES_PASSWORD: 'nekopassword'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    depends_on:
      - jpbft
    networks:
      - nekonet


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - jpbft
    networks:
      - nekonet


networks:
  nekonet:
    driver: bridge